version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
      #commands:
      # - There are no build commands
#  pre_build:
#    commands:
#      - pip install -r requirements.txt
  build:
    commands:
      - python3 test.py
#  post_build:
#    commands:
#      - python setup.py sdist bdist_wheel
